# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import billinfo_pb2 as billinfo__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestInfo = channel.unary_unary(
        '/billinfo.Greeter/RequestInfo',
        request_serializer=billinfo__pb2.BillRequest.SerializeToString,
        response_deserializer=billinfo__pb2.BillReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def RequestInfo(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestInfo': grpc.unary_unary_rpc_method_handler(
          servicer.RequestInfo,
          request_deserializer=billinfo__pb2.BillRequest.FromString,
          response_serializer=billinfo__pb2.BillReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'billinfo.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
