# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: billinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='billinfo.proto',
  package='billinfo',
  syntax='proto3',
  serialized_options=_b('\n\031io.grpc.examples.billinfoB\rBillInfoProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0e\x62illinfo.proto\x12\x08\x62illinfo\"\x1b\n\x0b\x42illRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tBillReply\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\x07Greeter\x12;\n\x0bRequestInfo\x12\x15.billinfo.BillRequest\x1a\x13.billinfo.BillReply\"\x00\x42\x32\n\x19io.grpc.examples.billinfoB\rBillInfoProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_BILLREQUEST = _descriptor.Descriptor(
  name='BillRequest',
  full_name='billinfo.BillRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='billinfo.BillRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_BILLREPLY = _descriptor.Descriptor(
  name='BillReply',
  full_name='billinfo.BillReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='billinfo.BillReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['BillRequest'] = _BILLREQUEST
DESCRIPTOR.message_types_by_name['BillReply'] = _BILLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BillRequest = _reflection.GeneratedProtocolMessageType('BillRequest', (_message.Message,), {
  'DESCRIPTOR' : _BILLREQUEST,
  '__module__' : 'billinfo_pb2'
  # @@protoc_insertion_point(class_scope:billinfo.BillRequest)
  })
_sym_db.RegisterMessage(BillRequest)

BillReply = _reflection.GeneratedProtocolMessageType('BillReply', (_message.Message,), {
  'DESCRIPTOR' : _BILLREPLY,
  '__module__' : 'billinfo_pb2'
  # @@protoc_insertion_point(class_scope:billinfo.BillReply)
  })
_sym_db.RegisterMessage(BillReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='billinfo.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=87,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestInfo',
    full_name='billinfo.Greeter.RequestInfo',
    index=0,
    containing_service=None,
    input_type=_BILLREQUEST,
    output_type=_BILLREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
